**Sonar Mine or Rock Prediction using Classification techniques**

The winner is SVM(linear)

In [113]:
import pandas as pd
import numpy as np

In [114]:
dataset = pd.read_csv("Sonar_Data.csv")

In [115]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.

In [116]:
dataset.isnull().sum().sum()

0

In [117]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [118]:
print(X)

[[0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.01   0.0171 0.0623 ... 0.0044 0.004  0.0117]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


In [119]:
print(y)

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']


In [120]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [121]:
print(y_test)

['R' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R'
 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M'
 'M' 'M' 'R' 'M' 'M' 'R']


Logistic Regression

In [122]:
X_train1 = X_train.copy()
y_train1 = y_train.copy()
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0)
classifier1.fit(X_train1, y_train1)
y_pred1 = classifier1.predict(X_test)

In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)
accuracy_score(y_test, y_pred1)

[[18  4]
 [ 6 14]]


0.7619047619047619

KNN

In [124]:
X_train2 = X_train.copy()
y_train2 = y_train.copy()
from sklearn.neighbors import KNeighborsClassifier 
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier2.fit(X_train2, y_train2)
y_pred2 = classifier2.predict(X_test)

In [125]:
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)
accuracy_score(y_test, y_pred2)

[[19  3]
 [ 8 12]]


0.7380952380952381

SVM

In [126]:
X_train3 = X_train.copy()
y_train3 = y_train.copy()
from sklearn.svm import SVC 
classifier3 = SVC(kernel = 'linear', random_state = 0)
classifier3.fit(X_train3, y_train3)
y_pred3 = classifier3.predict(X_test)

In [127]:
cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)
accuracy_score(y_test, y_pred3)

[[21  1]
 [ 7 13]]


0.8095238095238095

Kernel SVM

In [128]:
X_train4 = X_train.copy()
y_train4 = y_train.copy()
from sklearn.svm import SVC 
classifier4 = SVC(kernel = 'rbf', random_state = 0)
classifier4.fit(X_train4, y_train4)
y_pred4 = classifier4.predict(X_test)

In [129]:
cm4 = confusion_matrix(y_test, y_pred4)
print(cm4)
accuracy_score(y_test, y_pred4)

[[19  3]
 [ 7 13]]


0.7619047619047619

Naive Bayes


In [130]:
X_train5 = X_train.copy()
y_train5 = y_train.copy()
from sklearn.naive_bayes import GaussianNB 
classifier5 = GaussianNB()
classifier5.fit(X_train5, y_train5)
y_pred5 = classifier5.predict(X_test)

In [131]:
cm5 = confusion_matrix(y_test, y_pred5)
print(cm5)
accuracy_score(y_test, y_pred5)

[[15  7]
 [ 8 12]]


0.6428571428571429

Decision Tree

In [132]:
X_train6 = X_train.copy()
y_train6 = y_train.copy()
from sklearn.tree import DecisionTreeClassifier
classifier6 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier6.fit(X_train6, y_train6)
y_pred6 = classifier6.predict(X_test)

In [133]:
cm6 = confusion_matrix(y_test, y_pred6)
print(cm6)
accuracy_score(y_test, y_pred6)

[[20  2]
 [ 8 12]]


0.7619047619047619

Random Forest

In [135]:
X_train7 = X_train.copy()
y_train7 = y_train.copy()
from sklearn.ensemble import RandomForestClassifier 
classifier7 = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier7.fit(X_train7, y_train7)
y_pred7 = classifier7.predict(X_test)

In [136]:
cm7 = confusion_matrix(y_test, y_pred7)
print(cm7)
accuracy_score(y_test, y_pred7)

[[22  0]
 [ 9 11]]


0.7857142857142857